import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

let strings = new LocalizedStrings({

    en:{
        there:"There are 500 + labour close to your location",
        next:"NEXT",
        name:"Name",
        emailid:"Email Id",
        mobile:"Mobile",
        compnayname:"Company Name",
        register:"Register",
        already :"Already have an account?",
        sign :"Sign In",
        otp:"ENTER OTP",
        enter:"Please enter the verification code sent to your given mobile number",
        continue :"CONTINUE",
        resend :"Resend Otp ?",
        enrolling:"Thank you for enrolling with us",
        agree:"Our sales team will contact you shortly for our service agreement",
        welcome:"Welcome Login",
        service:"Service Contract Number",
        select:"Select Role",
        login:"Login",
        dont :"Don't have an account?",
        associate:"Associate with us",
        password:"Password",
        please:"can not be blank. Please enter",
        unable:"Unable to process your Request Please try again after some time.",
        about :"About Us",
        support :"Support",
        terms :"Terms & Condition",
        privacy :"Privacy Policy",
        logout :"Logout",
        setting:"Settings",
        create:"My Earning",
        booking:"Current Jobs",
        invoice:"Add Supervisior",
        approval:"Add Labour",
        dlr:"Rate Chart",
        dpr:"Statutory",
        click:"Click to Enter",
        option:"Choose Option for which you have to create request.",
        muster :"Labour on Muster",
        measure:"Labour on Measurement",
        selectContract:"Select Contract No. ",
        selectCategory:"Select Category ",
        expectedStart:"Expected start date of work",
        expectedEnd:"Expected End date of work",
        site:"Is Site Accomodation Provided",
        transport:"Is transport Provided",
        submit:"Submit",
        noof:"Select Category Expertise",
        labourCategory :"Labour Category",
        nooflabour :"No. of Labour",
        add :"+ Add More",
        welcomehome :"Welcome",
        projectName :"Project Name",
        homeLocation :"Location",
        twoone:"We do not serve customers without site accomodation in line with guidelines of BOCW act",
        twotwo:"We do not serve customers without site accomodation in line with guidelines of BOCW act",
        onetwo:"We presume the accomodation is within site premises and no tranportation is required. In case the accomodation distance is more than 1.5 km then the transportation has to be arranged by customer.",
        ok:"OK",
        confirmBooking:"We confirm your booking. You would be provided with workforce details within 24 hours",
        bookingId:"Your Booking Id:",
        myBooking:"My Booking",
        date:"Date",
        time:"Time",
        requestno:"Request No",
        bid:"Booking Id",
        labourDetail :'Labour Details',
        totalno:"Total No. of Days",
        noofday:"No. of Days Worked",
        remaing:'No. of Days Remaining',
        assocated:'List of Associated Contractor',
        invoiceno:"Invoice no",
        approvals:"Invoice Approval Request",
        invoiceDetails:"Invoice Details",
        approved:"Mark Approved",
        message:"Message to be Speak:",
        attendance:"Attendance Approval Request",
        approvalDetail :"Approval Details",
        total:"Total No. of Labours -",
        dlrs:"Daily Labour Report",
        bookingIds:"Booking Id:",
        cid:"Contractor ID",
        doa:"Date of Attendance",
        sr:"Thank you for submitting Report",
        dprs:"Daily Progress Report",
        reportingdate:"Reporting Date",
        code:"Select Item Code & Name",
        work:"Work",
        productivity:"Productivity",
        statutory:"Statutory",
        totalinvo:"Total Invoiced",
        totalpaid:"Total Paid",
        bd:"Balance Due",
        report:"Reports",
        invoiceRaised:"Invoice Raised",
        prn:"Payment Receipt Note",
        consolidated :"Consolidated Productivity",
        trade:"TradeWise",
        contractor:"Contractor Wise",
        welocmes:"Welcome to Labour Home",
        india:"India's First Online Labour Pool",
        signup:"Signup",
        thereare:"There are",
        close:"Labour close to your location",
        closed:"Job close to your location",
        profile:"Profile",
        services:"Service Agreement :",
        attendancesheet:"Attendance ",
        wage:"Muster Roll",
        pf:"PF ",
        esi:"ESI ",
        attendanceReport:"Attendance Report",
        monthlyAttendance:"Monthly Attendance Report",
        cname:"Contractor Name",
        year:"Year",
        month:"Month",
        labourid:"Labour Id",
        totalpresent:"Total Present",
        totalabsent:"Total Absent",
        download:"Download Pdf",
        detail:"Detail",
        yearly:"Yearly PF Remittance",
        selectm:"Select Month",
        pfd :"PF Document",
        admin:"Service Contract number is not generated Please Contact to admin.",
        notific:"Notification",
        attDetail:"Attendance Detail",
        forgot:"Forgot Password",
        forgotDesc:"Please enter your email below to receive new password",
        send:"Send Request",
        age:"Age",
        experience:"Experience",
        address:"Address",
        city:"City",
        state:"State",
        pincode:"Pin Code",
        jobe:"Job Expertise",
        upload:"Upload Id Card",
        uploadPhoto :"Upload Photo",
        rid:"Registration ID",
        earning:'Earning',
        totalearning:'Total Earning',
        bill:"Bill of Supply",
        ir :'Invoice raised for booking id # ',
        supervisiorList:'Supervisior List',
        createSuper:'Create Supervisor',
        idcard :'ID Card',
        mrc:'Monthly Rate Chart',
        zone:'Select Zone',
        labourList:'Labour List',
        addLabour :"Add Labour",
        subcategory :'Select SubCategory',
        jobid:'Select Job Id',
        mark :'Mark Daily Attendance',
        jobs :'Jobs',
        locationMap :'Location Map',
        accept :'Accept Request',
        decline :'Decline Request',
        pfs :'PF Documents for Selected month',
        esid :'ESI Document',
        esis :'ESI Document for Selected Month',
        assignl :'Assign Labour',
        assigns :'Assign Supervisior',
        registrationid :'Registration Id',
        update:'Updates',
        labourlaw:"Labour Law",
        news:"News",
        article:'Article',
        mustersheet:'Choose Option for Muster Sheet',
        downloads :'Download Muster Sheet',
        uploadsig :"Upload Signed Muster Sheet",




    },
    hi: {
        there:"आपके स्थान के करीब 500 + श्रम हैं",
        next:"आगामी",
        name:"नाम",
        emailid:"ईमेल आईडी",
        mobile:"मोबाइल",
        compnayname:"कंपनी का नाम",
        register:"रजिस्टर",
        already :"पहले से ही एक खाता है?",
        sign :"दाखिल करना",
        otp:"OTP दर्ज करें",
        enter:"कृपया अपने दिए गए मोबाइल नंबर पर भेजा गया सत्यापन कोड डालें",
        continue:"जारी रहना",
        resend :"परिणाम OTP ?",
        enrolling:"हमारे साथ नामांकन करने के लिए धन्यवाद",
        agree:"हमारी सेवा समझौते के लिए हमारी बिक्री टीम आपसे शीघ्र ही संपर्क करेगी",
        welcome:"आपका स्वागत है लॉगिन करें",
        service:"सेवा अनुबंध संख्या",
        select:"भूमिका का चयन करें",
        login:"लॉग इन करें",
        dont :"खाता नहीं है?",
        associate:"हमारे साथ जुड़े",
        password:"पारण शब्द",
        please:"रिक्त नहीं हो सकता कृपया दर्ज करें",
        unable:"आपका अनुरोध संसाधित करने में असमर्थ कृपया कुछ समय बाद पुन: प्रयास करें।",
        about :"हमारे बारे में",
        support :"समर्थन",
        terms :"नियम व शर्त",
        privacy :"गोपनीयता नीति",
        logout :"लोग आउट",
        setting:"सेटिंग्स",
        create:"मेरी कमाई",
        booking:"वर्तमान नौकरियां",
        invoice:"पर्यवेक्षक जोड़ें",
        approval:"पर्यवेक्षक जोड़ें",
        dlr:"रेट चार्ट",
        dpr:"वैधानिक",
        click:"दर्ज करने के लिए क्लिक करें",
        option:"विकल्प चुनें जिसके लिए आपको अनुरोध बनाना होगा।",
        muster :"मस्टर पर श्रम",
        measure:"माप पर श्रम",
        selectContract:"संविदा का चयन करें",
        selectCategory:"श्रेणी का चयन करें ",
        expectedStart:"काम की शुरुआत की तारीख की उम्मीद",
        expectedEnd:"काम की अंतिम तिथि की उम्मीद",
        site:"क्या साइट आवास प्रदान किया गया है",
        transport:"परिवहन प्रदान किया जाता है",
        submit:"जमा करें",
        noof:"श्रेणी विशेषज्ञता का चयन करें",
        labourCategory :"श्रम की श्रेणी",
        nooflabour :"No. of Labour",
        add :"+ और जोड़ें",
        welcomehome :"स्वागत",
        projectName :"परियोजना का नाम",
        homeLocation :"स्थान",
        twoone:"हम बीओसीडब्ल्यू अधिनियम के दिशानिर्देशों के अनुरूप साइट के बिना ग्राहकों की सेवा नहीं करते हैं",
        twotwo:"हम बीओसीडब्ल्यू अधिनियम के दिशानिर्देशों के अनुरूप साइट के बिना ग्राहकों की सेवा नहीं करते हैं",
        onetwo:"हम मानते हैं कि साइट स्थल के भीतर ही निवास स्थान है और किसी भी प्रकार के परिवहन की आवश्यकता नहीं है। यदि आवास की दूरी 1.5 किमी से अधिक है, तो परिवहन की व्यवस्था ग्राहक द्वारा की जानी चाहिए।",
        ok:"ठीक",
        confirmBooking:"हम आपकी बुकिंग की पुष्टि करते हैं। आपको 24 घंटे के भीतर कार्यबल विवरण प्रदान किया जाएगा",
        bookingId:"आपकी बुकिंग आईडी:",
        myBooking:"मेरी बुकिंग",
        date:"दिनांक",
        time:"पहर",
        requestno:"अनुरोध नं",
        bid:"बुकिंग आईडी",
        labourDetail :'Labours Details',
        totalno:"कुल दिनों की संख्या",
        noofday:"काम के दिनों की संख्या",
        remaing:'शेष दिन की संख्या',
        invoiceno:"चालान नंबर",
        approvals:"चालान स्वीकृति अनुरोध",
        invoiceDetails:"चालान विवरण",
        approved:"मार्क स्वीकृत",
        message:"बोलने के लिए संदेश:",
        attendance:"उपस्थिति अनुमोदन अनुरोध",
        approvalDetail :"अनुमोदन विवरण",
        total:"मजदूरों की कुल संख्या -",
        dlrs:"दैनिक श्रम रिपोर्ट",
        bookingIds:"बुकिंग आईडी",
        cid:"ठेकेदार आईडी",
        doa:"उपस्थिति की तारीख",
        sr:"रिपोर्ट प्रस्तुत करने के लिए धन्यवाद",
        dprs:"दैनिक प्रगति रिपोर्ट",
        reportingdate:"सूचना देने की नियत तिथि",
        code:"आइटम कोड और नाम का चयन करें",
        work:"काम",
        productivity:"उत्पादकता",
        statutory:"वैधानिक",
        totalinvo:"कुल चालान",
        totalpaid:"कुल भुगतान हो गया",
        bd:"शेष राशि",
        report:"रिपोर्ट",
        invoiceRaised:"चालान उठाया गया",
        prn:"भुगतान रसीद नोट",
        consolidated :"समेकित उत्पादकता",
        trade:"TradeWise",
        contractor:"ठेकेदार Wise",
        welocmes:"लेबर होम में आपका स्वागत है",
        india:"भारत का पहला ऑनलाइन लेबर पूल",
        signup:"पंजीकरण",
        thereare:"आपके स्थान के करीब",
        close:"लेबर हैं।",
        closed:"काम हैं।",
        profile:"प्रोफाइल",
        services:"सेवा अनुबंध :",
        attendancesheet:"उपस्थिति ",
        wage:"मस्टर रोल",
        pf:"पीएफ ",
        esi:"ईएसआई ",
        attendanceReport:"उपस्थिति विवरण",
        monthlyAttendance:"मासिक उपस्थिति रिपोर्ट",
        cname:"ठेकेदार का नाम",
        year:"साल",
        month:"महीना",
        labourid:"लेबर आईडी",
        totalpresent:"कुल वर्तमान",
        totalabsent:"कुल अनुपस्थित",
        download:"पीडीएफ़ डाउनलोड करें",
        detail:"विस्तार",
        yearly:"वार्षिक पीएफ प्रेषण",
        selectm:"महीना चुनिए",
        pfd :"पीएफ दस्तावेज़",
        admin:"सेवा अनुबंध संख्या जेनरेट नहीं हुई है। कृपया व्यवस्थापक से संपर्क करें।",
        notific:"अधिसूचना",
        attDetail:'Attendance Detail',
        forgot:"पासवर्ड भूल गए",
        forgotDesc:"नया पासवर्ड प्राप्त करने के लिए कृपया नीचे अपना ईमेल दर्ज करें",
        send:"अनुरोध भेजा",
        age:"आयु",
        experience:"अनुभव",
        address:"पता",
        city:"शहर",
        state:"राज्य",
        pincode:"पिन कोड",
        jobe:"नौकरी विशेषज्ञता",
        upload:"आईडी कार्ड अपलोड करें",
        uploadPhoto :"फोटो अपलोड करें",
        rid:"पंजीयन पहचान",
        earning:'कमाई',
        totalearning:'कुल कमाई',
        bill:"आपूर्ति का बिल",
        ir :'बुकिंग आईडी के लिए उठाया गया चालान # ',
        supervisiorList:'पर्यवेक्षण सूची',
        createSuper:'पर्यवेक्षक बनाएं',
        idcard :'पहचान पत्र',
        mrc:'मासिक दर चार्ट',
        zone:'ज़ोन का चयन करें',
        labourList: 'श्रम सूची',
        addLabour : "श्रम जोड़ें",
        subcategory :'उपश्रेणी का चयन करें ',
        jobid:'जॉब आईडी चुनें',
        mark :'मार्क डेली अटेंडेंस',
        jobs :'नौकरियां',
        locationMap :'स्थान मानचित्र',
        accept :'अनुरोध स्वीकार करें',
        decline :'अनुरोध अस्वीकार करें',
        pfs :'चयनित महीने के लिए पीएफ दस्तावेज़',
        esid :'ईएसआई दस्तावेज़',
        esis :'चयनित माह के लिए ईएसआई दस्तावेज़',
        assignl :'श्रम सौंपें',
        assigns :'पर्यवेक्षक को सौंपें',
        registrationid :'पंजीयन पहचान',
        update:'अपडेट',
        labourlaw:"श्रम कानून",
        news:"समाचार",
        article:'लेख',
        mustersheet:'मस्टर शीट के लिए विकल्प चुनें',
        downloads : 'मस्टर शीट डाउनलोड करें',
        uploadsig :"अपलोड की गई मस्टर शीट",
        //मेरी बुकिंग
    }
});
export default strings;